project:
  # Use "book" instead of "website" to get a left sidebar of chapters
  type: book
  output-dir: docs

book:
  # Global title (appears at the top of the sidebar)
  title: "LaTeX 1"
  author: "Your Name"
  repo-url: https://github.com/HaykTarkhanyan/latex_tutorial
  repo-actions: [edit]
  # downloads: [pdf, epub]
  
  
  # Define chapters (top-level pages) and sub-chapters
  chapters:
    - index.qmd
    - part: "Tutorials"
      chapters:
        - tutorials/armenian.qmd
        - tutorials/basics.qmd
        - tutorials/advanced.qmd

format:
  html:
    # Pick a theme you like, e.g., "cosmo", "flatly", "minty", etc.
    theme:
      light: cosmo   # light mode theme
      dark: darkly   # dark mode theme
    dark-mode-toggle: true
    dark-mode-toggle-position: right
    # Show table of contents on the left
    toc: true
    toc-location: right

    # Optional: Control sidebar depth or other options
    number-sections: true
    code-fold: true
